version: 0.2

env:
  variables:
    AWS_REGION: "ca-central-1"
    AWS_ACCOUNT_ID: "634898291773"
    IMAGE_REPO_NAME: "sandhu-assn3"

phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo Creating imagedefinitions.json for ECS deployment...
      - printf '[{"name":"container","imageUri":"%s.dkr.ecr.%s.amazonaws.com/%s:latest"}]' $AWS_ACCOUNT_ID $AWS_REGION $IMAGE_REPO_NAME > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
